import { Routes } from '@angular/router';
import { BodegaComponent } from './pages/bodega/bodega';
import { CatalogoComponent } from './pages/catalogo/catalogo';
import { CategoriasComponent } from './pages/categorias/categorias';
import { DashboardComponent } from './pages/dashboard/dashboard';
import { LoginComponent } from './pages/login/login';
import { MensajesComponent } from './pages/mensajes/mensajes';
import { NotFoundComponent } from './pages/not-found/not-found';
import { PedidosComponent } from './pages/pedidos/pedidos';
import { TiendaComponent } from './pages/tienda/tienda';
import { UsuariosComponent } from './pages/usuarios/usuarios';
import { VentasComponent } from './pages/ventas/ventas';
import { VendedorComponent } from './pages/vendedor/vendedor';
import { MiCuentaComponent } from './pages/mi-cuenta/mi-cuenta';
import { ProductosClienteComponent } from './pages/productos-cliente/productos-cliente';
import { CarritoComponent } from './pages/carrito/carrito';

export const routes: Routes = [
  { path: '', component: TiendaComponent },
  { path: 'login', component: LoginComponent },
  { path: 'tienda', component: TiendaComponent },
  { path: 'admin', component: DashboardComponent },
  { path: 'vendedor', component: VendedorComponent },
  { path: 'bodega', component: BodegaComponent },
  { path: 'catalogo', component: CatalogoComponent },
  { path: 'categorias', component: CategoriasComponent },
  { path: 'usuarios', component: UsuariosComponent },
  { path: 'ventas', component: VentasComponent },
  { path: 'pedidos', component: PedidosComponent },
  { path: 'mensajes', component: MensajesComponent },
  { path: 'mi-cuenta', component: MiCuentaComponent },
  { path: 'productos', component: ProductosClienteComponent },
  { path: 'carrito', component: CarritoComponent },
  { path: '404', component: NotFoundComponent },
  { path: '**', redirectTo: '404' },
];
